### ISSUE TITLE
C710 touchpad driver not working

### ISSUE THREAD

**Issue by kered424** [coolstar/crostouchpad4#5]
Clean install of Win10/11, used the latest 4.1.6 driver installer, and the touchpad just does not work period. I'm on the latest version of Mr.Chromebox firmware 4.22.4. I've also force installed older versions of the driver, but it still doesn't work.

Touchpad works fine out of the box on Ubuntu, so it doesn't seem like a hardware issue.

Happy to provide any additional info.

**Comment by coolstar** [comment]
C710 touchpad driver is at https://github.com/coolstar/crostouchpad4-smbus, not this one. I'll test on my C710 however and update this comment with my findings
